version: '3'

services:
    # NestJS application
    app:
        build:
            context: .
            dockerfile: './docker/app/Dockerfile'
        container_name: 'skote_app'
        volumes:
            - './app:/var/www/app'
            - './docker/app/entrypoint.sh:/entrypoint.sh'
        working_dir: '/var/www/app'
        networks:
            - skote
        ports:
            - '3000:3000'
        expose:
            - '3000'
        links:
            - 'db'
        depends_on:
            - 'db'
        command: ['/entrypoint.sh']

    # MySQL database
    db:
        build:
            context: .
            dockerfile: './docker/db/Dockerfile'
        container_name: 'skote_db'
        volumes:
            - 'skote-mysql:/var/lib/mysql'
        networks:
            - skote
        environment:
            TZ: '${APP_TIMEZONE:-UTC}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "${FORWARD_DB_PORT:-13306}:3306"
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
networks:
    skote:
        driver: bridge
volumes:
    skote-mysql: # Use mysql local (must install mysql local to use)
        driver: local
    skote-redis:
        driver: local
    dependencies:
