version: '3'

services:
    # MySQL database
    db:
        build:
            context: .
            dockerfile: './docker/db/Dockerfile'
        container_name: 'skote_db'
        volumes:
            - 'skote-mysql:/var/lib/mysql'
        networks:
            - skote
        environment:
            TZ: '${APP_TIMEZONE:-UTC}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
        ports:
            - "${FORWARD_DB_PORT:-13306}:3306"
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
networks:
    skote:
        driver: bridge
volumes:
    skote-mysql: # Use mysql local (must install mysql local to use)
        driver: local
    skote-redis:
        driver: local
    dependencies:
